name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Test
        run: echo "Everything is fine"

      - name: Step 4 - Scan for Application Secrets
        run: |
          docker run --rm \
          -v "${GITHUB_WORKSPACE}/application:/repo" \
          ghcr.io/gitleaks/gitleaks:latest \
          detect \
          --source=/repo \
          --no-git \
          --no-banner \
          --exit-code 1